const ROUTES = {
  HOME: "/" as const,
  ONBOARDING: "/onboarding" as const,
  LISTING: "/barbers" as const,
  BARBER: "/barber" as const,
  AUTH: "/(auth)" as const,
  BOOKING_MANAGEMENT: "/bookings/manage" as const,
  // BOOKING_CANCEL: "/bookings/cancel" as const,
  NEW_BOOKING: "/new-booking" as const,
  REVIEWS: "/reviews" as const,
  NEW_BOOKING_CONFIRM_AND_PAY: "/new-booking/confirm-and-pay" as const,
  NEW_BOOKING_ADD_CARD: "/new-booking/confirm-and-pay/add-card" as const,
  NEW_BOOKING_CHOOSE_CARD: "/new-booking/confirm-and-pay/choose-card" as const,
  NEW_BOOKING_PAYMENT_SUCCESS: "/bookings/success" as const,
  PROFILE: "/profile" as const,
  BOOKING_HISTORY: "/profile/booking-history" as const,
  ORDER_HISTORY: "/profile/order-history" as const,
  PERSONAL_INFO: "/profile/personal-info" as const,
  MANAGE_NOTIFICATIONS: "/profile/manage-notifications" as const,
  // PAYMENT_METHODS: "/profile/payment-methods" as const,
  // COUPONS: "/profile/payment-methods/coupons" as const,
  // CARDS: "/profile/payment-methods/cards" as const,
  // ADD_NEW_CARD: "/profile/payment-methods/cards/add-new" as const,
  // GIFT_CARDS: "/profile/payment-methods/gift-cards" as const,
  // ADD_NEW_GIFT_CARD: "/profile/payment-methods/gift-cards/buy" as const,
  TERMS: "/profile/terms-and-conditions" as const,
  ASSISTANCE: "/profile/assistance" as const,
  NOTIFICATIONS: "/profile/notifications" as const,
  PAYMENT: "/payment" as const,
  PAYMENT_WEB: "https://pagamenti-v3.netlify.app" as const,
  GIFTS: "/gifts" as const,
  SHOP: "/shop" as const,
  CART: "/cart" as const,
};

export default ROUTES;
